include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

before_script:
  - npm ci
  - npm run build

cache:
  paths:
    - node_modules/

test:
  image: node:$NODE_VERSION
  script:
    # Workaround to ava bug: https://github.com/avajs/ava/issues/2415
    - unset CI_NODE_INDEX
    - unset CI_NODE_TOTAL
    - npm t
  parallel:
    matrix:
      - NODE_VERSION: [10, 11, 12, 13, 14, 15]